pipeline {
    agent any

    stages {
        stage('Checkout Code') {
            steps {
                git 'https://github.com/Shardulkacheria/DEVOPS-'
            }
        }
        stage('Build Docker Image') {
            steps {
                bat 'docker build -t hello-devops .'
            }
        }
        stage('Run Docker Container') {
            steps {
                bat 'docker rm -f devops-container || exit 0'
                bat 'docker run -d -p 5000:3000 --name devops-container hello-devops'
            }
        }
    }
}
