pipeline {
    agent any

    stages {
        stage('Clone Repo') {
            steps { git 'https://github.com/Shardulkacheria/DEVOPS-' }
        }
        stage('Build Docker Image') {
            steps { sh 'docker build -t hello-devops ./app' }
        }
        stage('Run Container') {
            steps { sh 'docker run -d -p 5000:3000 --name devops hello-devops' }
        }
    }
}
